// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	Version
	Message
	Empty
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Version struct {
	SemVer    string `protobuf:"bytes,1,opt,name=sem_ver,json=semVer" json:"sem_ver,omitempty"`
	GitCommit string `protobuf:"bytes,2,opt,name=git_commit,json=gitCommit" json:"git_commit,omitempty"`
}

func (m *Version) Reset()                    { *m = Version{} }
func (m *Version) String() string            { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()               {}
func (*Version) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Version) GetSemVer() string {
	if m != nil {
		return m.SemVer
	}
	return ""
}

func (m *Version) GetGitCommit() string {
	if m != nil {
		return m.GitCommit
	}
	return ""
}

type Message struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Message) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// TODO - remove this message type and use google.protobuf.Empty
type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*Version)(nil), "rpc.Version")
	proto.RegisterType((*Message)(nil), "rpc.Message")
	proto.RegisterType((*Empty)(nil), "rpc.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for KTK service

type KTKClient interface {
	GetVersion(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Version, error)
	ServerStream(ctx context.Context, in *Empty, opts ...grpc.CallOption) (KTK_ServerStreamClient, error)
}

type kTKClient struct {
	cc *grpc.ClientConn
}

func NewKTKClient(cc *grpc.ClientConn) KTKClient {
	return &kTKClient{cc}
}

func (c *kTKClient) GetVersion(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Version, error) {
	out := new(Version)
	err := grpc.Invoke(ctx, "/rpc.KTK/GetVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kTKClient) ServerStream(ctx context.Context, in *Empty, opts ...grpc.CallOption) (KTK_ServerStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_KTK_serviceDesc.Streams[0], c.cc, "/rpc.KTK/ServerStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &kTKServerStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type KTK_ServerStreamClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type kTKServerStreamClient struct {
	grpc.ClientStream
}

func (x *kTKServerStreamClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for KTK service

type KTKServer interface {
	GetVersion(context.Context, *Empty) (*Version, error)
	ServerStream(*Empty, KTK_ServerStreamServer) error
}

func RegisterKTKServer(s *grpc.Server, srv KTKServer) {
	s.RegisterService(&_KTK_serviceDesc, srv)
}

func _KTK_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KTKServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.KTK/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KTKServer).GetVersion(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _KTK_ServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KTKServer).ServerStream(m, &kTKServerStreamServer{stream})
}

type KTK_ServerStreamServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type kTKServerStreamServer struct {
	grpc.ServerStream
}

func (x *kTKServerStreamServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

var _KTK_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.KTK",
	HandlerType: (*KTKServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _KTK_GetVersion_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerStream",
			Handler:       _KTK_ServerStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0x31, 0x0b, 0xc2, 0x30,
	0x10, 0x85, 0x5b, 0x8b, 0x0d, 0x3d, 0x3a, 0x65, 0xb1, 0x08, 0x82, 0xc4, 0xa5, 0x83, 0x14, 0xd1,
	0x5f, 0x20, 0x22, 0x0e, 0xc5, 0xc5, 0x4a, 0x37, 0x29, 0xb5, 0x1c, 0x25, 0x43, 0x4c, 0xb8, 0x84,
	0x82, 0xff, 0x5e, 0x8c, 0xed, 0xe6, 0xf6, 0xee, 0xde, 0xe3, 0xbe, 0x7b, 0x90, 0x90, 0xe9, 0x0a,
	0x43, 0xda, 0x69, 0x1e, 0x91, 0xe9, 0xc4, 0x11, 0x58, 0x8d, 0x64, 0xa5, 0x7e, 0xf1, 0x05, 0x30,
	0x8b, 0xaa, 0x19, 0x90, 0xb2, 0x70, 0x1d, 0xe6, 0xc9, 0x2d, 0xb6, 0xa8, 0x6a, 0x24, 0xbe, 0x02,
	0xe8, 0xa5, 0x6b, 0x3a, 0xad, 0x94, 0x74, 0xd9, 0xcc, 0x7b, 0x49, 0x2f, 0xdd, 0xc9, 0x2f, 0xc4,
	0x06, 0xd8, 0x15, 0xad, 0x6d, 0x7b, 0xe4, 0x19, 0x30, 0xf5, 0x93, 0xe3, 0x89, 0x69, 0x14, 0x0c,
	0xe6, 0x67, 0x65, 0xdc, 0x7b, 0xff, 0x80, 0xa8, 0xbc, 0x97, 0x3c, 0x07, 0xb8, 0xa0, 0x9b, 0xd0,
	0x50, 0x7c, 0xdf, 0xf2, 0x81, 0x65, 0xea, 0xf5, 0xe8, 0x88, 0x80, 0x6f, 0x21, 0xad, 0x90, 0x06,
	0xa4, 0xca, 0x11, 0xb6, 0xea, 0x4f, 0x76, 0xa4, 0x8b, 0x60, 0x17, 0x3e, 0x63, 0xdf, 0xed, 0xf0,
	0x09, 0x00, 0x00, 0xff, 0xff, 0x54, 0x8a, 0x2b, 0xe2, 0xe8, 0x00, 0x00, 0x00,
}
